### ISSUE TITLE
Support `JavaModule`s

### ISSUE THREAD

**Issue by lefou** [lolgab/mill-mima#154]
`mill-mima` can also be used to check binary compatibility of Java modules. This is possible since MiMa checks the resulting bytecode, not the source code.

The current setup is a bit inconvenient for Java-only modules, since trait `MiMa` already extends `ScalaModule`. I think, it's safe to not extend `ScalaModule`. Extending `JavaModule` should be enough.

@lolgab WDYT?

**Comment by lolgab** [comment]
If it's useful for Java as well, I don't have anything against the change.
We have a check that uses `scalaVersion()`, is it possible to call it if the module is a `ScalaModule`? If not, I'm ok removing it.. At the end it is ok with every Scala version out there..
