### ISSUE TITLE
`mimaExcludeAnnotations` doesn't work with `object`s

### ISSUE THREAD

**Issue by lolgab** [lolgab/mill-mima#41]
Since the implementation seems the same as Sbt Mima, my best guess is that there is some dependency clash that creates it.
The next thing I'm going to try is to run the tool from an insulated classloader.

### Edit
Blocked by https://github.com/lightbend/mima/issues/689

**Comment by lefou** [comment]
This might be related to 

* #6

Also, once you isolate the MiMa classloader from Mill, you need to provide some other way to configure exclusions.

**Comment by lolgab** [comment]
I'm replicating the MiMa classes instances here and make the same API available (except for the mima imports).
Let's see how it goes.

**Comment by lefou** [comment]
Oh, ok. Is this something not possible or is it just a missing feature from MiMa? Any links?

Lots of work to find out, but at least, it is not for nothing. Having MiMa as a worker will keep the Mill classloader lighter and allows for easier MiMa version bumps (without new mill-mima releases). :+1:

**Comment by lolgab** [comment]
Yes, I like the classloader change either way :-) I think we should make it easier to write plugins with the implementation in a separate classloader so it can become the new default.

About the Mima bug, I couldn't find anything, so I'm opening one right now.

**Comment by lefou** [comment]
Some of my annotations which I think were ignored were on `def`s in `trait`s. The annotations were `scala.annotation.StaticAnnotation`. I don't know if this is visible enough for MiMa, or if they need to be written in Java. I didn't find any info about that.

**Comment by lolgab** [comment]
I think `StaticAnnotation`s are fine because tests use them, but maybe `trait`s aren't supported as well as `object`s.
Also the annotation should be present already in the previous version, adding it at a later point doesn't work.

**Comment by lefou** [comment]
Thanks for these information.
